language: node_js
# nodejs的版本
node_js:
  - "iojs"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

# S: Build Lifecycle
install:
  - npm install


before_install:
  - export TZ='Asia/Shanghai'  # 设置时区
  - npm install -g hexo
  - npm install -g hexo-cli

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "old-king"
  - git config user.email "oldking1116@hotmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - dev

cache:
  directories:
    - node_modules
env:
 global:
   - GH_REF: github.com/old-king/old-king.github.io.git